name: aws_polly_example
description: Demonstrates how to use the aws_polly plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.9.20

dev_dependencies:
  aws_polly:
    path: ../

flutter:
  uses-material-design: true
